import {
  Document,
  Page,
  renderToBuffer,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

import type { ReportData } from "./data";
import { buildWeeklySummary } from "./data";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#141F1B" },
  title: { fontSize: 20, marginBottom: 4, color: "#0B7A54" },
  subtitle: { fontSize: 11, marginBottom: 16, color: "#4B5B54" },
  sectionTitle: { fontSize: 13, marginTop: 16, marginBottom: 6, color: "#0B7A54" },
  statRow: { flexDirection: "row", gap: 12, marginBottom: 8 },
  statBox: {
    flexGrow: 1,
    padding: 8,
    backgroundColor: "#EDF3F0",
    borderRadius: 4,
  },
  statLabel: { fontSize: 8, color: "#4B5B54", marginBottom: 2 },
  statValue: { fontSize: 14 },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#C6D4CD",
    paddingVertical: 4,
    fontFamily: "Helvetica-Bold",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#DCE7E1",
    paddingVertical: 3,
  },
  colDate: { width: "20%" },
  colNum: { width: "16%", textAlign: "right" },
  entryRow: { flexDirection: "row", paddingVertical: 2, paddingLeft: 8 },
  colMeal: { width: "18%", color: "#4B5B54" },
  colItem: { width: "50%" },
  footer: { position: "absolute", bottom: 24, left: 40, fontSize: 8, color: "#8A9A92" },
});

function fmt(value: number | undefined | null): string {
  return value == null ? "-" : String(Math.round(value));
}

export function ReportDocument({ data }: { data: ReportData }) {
  const summary = buildWeeklySummary(data);
  return (
    <Document title={`MacroMap report ${data.from} to ${data.to}`}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>MacroMap Report</Text>
        <Text style={styles.subtitle}>
          {data.from} to {data.to} · {summary.daysLogged} days logged
        </Text>

        <View style={styles.statRow}>
          <View style={styles.statBox}>
            <Text style={styles.statLabel}>Avg calories / day</Text>
            <Text style={styles.statValue}>{fmt(summary.averages.calories)}</Text>
          </View>
          <View style={styles.statBox}>
            <Text style={styles.statLabel}>Avg protein (g)</Text>
            <Text style={styles.statValue}>{fmt(summary.averages.proteinG)}</Text>
          </View>
          <View style={styles.statBox}>
            <Text style={styles.statLabel}>Avg carbs (g)</Text>
            <Text style={styles.statValue}>{fmt(summary.averages.carbsG)}</Text>
          </View>
          <View style={styles.statBox}>
            <Text style={styles.statLabel}>Avg fat (g)</Text>
            <Text style={styles.statValue}>{fmt(summary.averages.fatG)}</Text>
          </View>
          <View style={styles.statBox}>
            <Text style={styles.statLabel}>Weight change</Text>
            <Text style={styles.statValue}>
              {summary.weightChange == null ? "-" : summary.weightChange}
            </Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Daily totals</Text>
        <View style={styles.tableHeader}>
          <Text style={styles.colDate}>Date</Text>
          <Text style={styles.colNum}>Calories</Text>
          <Text style={styles.colNum}>Protein g</Text>
          <Text style={styles.colNum}>Carbs g</Text>
          <Text style={styles.colNum}>Fat g</Text>
          <Text style={styles.colNum}>Sodium mg</Text>
        </View>
        {data.days.map((day) => (
          <View key={day.date} style={styles.tableRow}>
            <Text style={styles.colDate}>{day.date}</Text>
            <Text style={styles.colNum}>{fmt(day.totals.calories)}</Text>
            <Text style={styles.colNum}>{fmt(day.totals.proteinG)}</Text>
            <Text style={styles.colNum}>{fmt(day.totals.carbsG)}</Text>
            <Text style={styles.colNum}>{fmt(day.totals.fatG)}</Text>
            <Text style={styles.colNum}>{fmt(day.totals.sodiumMg)}</Text>
          </View>
        ))}

        {data.weights.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Weight log</Text>
            <View style={styles.tableHeader}>
              <Text style={styles.colDate}>Date</Text>
              <Text style={styles.colNum}>Weight</Text>
            </View>
            {data.weights.map((weight) => (
              <View key={weight.id} style={styles.tableRow}>
                <Text style={styles.colDate}>{weight.date}</Text>
                <Text style={styles.colNum}>{weight.weightValue}</Text>
              </View>
            ))}
          </>
        )}

        <Text style={styles.footer} fixed>
          Generated by MacroMap
        </Text>
      </Page>

      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Diary detail</Text>
        {data.days
          .filter((day) => day.entries.length > 0)
          .map((day) => (
            <View key={day.date} wrap={false}>
              <View style={styles.tableHeader}>
                <Text style={styles.colDate}>{day.date}</Text>
                <Text style={{ ...styles.colNum, width: "80%" }}>
                  {fmt(day.totals.calories)} kcal
                </Text>
              </View>
              {day.entries.map((entry, index) => (
                <View key={index} style={styles.entryRow}>
                  <Text style={styles.colMeal}>{entry.mealName}</Text>
                  <Text style={styles.colItem}>{entry.label}</Text>
                  <Text style={styles.colNum}>{fmt(entry.nutrition.calories)} kcal</Text>
                  <Text style={styles.colNum}>{fmt(entry.nutrition.proteinG)} g pro</Text>
                </View>
              ))}
            </View>
          ))}
        <Text style={styles.footer} fixed>
          Generated by MacroMap
        </Text>
      </Page>
    </Document>
  );
}

export async function generateReportPdf(data: ReportData): Promise<Buffer> {
  return renderToBuffer(<ReportDocument data={data} />);
}
